import { expect, it } from "vitest";

import { processVizdomSvg } from "../src/vizdom";

const svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by vizdom version 10.0.1 (0)
 -->
<!-- Title: G Pages: 1 -->
<svg width="79pt" height="116pt"
 viewBox="0.00 0.00 79.41 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-112 75.41,-112 75.41,4 -4,4"/>
<!-- Hello -->
</g>
</svg>`;

it("removes xml doctype", async () => {
  const result = processVizdomSvg(svg);

  expect(result).toMatchInlineSnapshot(
    `"<figure class="beoe vizdom "><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 79.41 116"><g class="graph" transform="translate(4 112)"><path fill="#fff" d="M-4 4v-116h79.41V4z"/></g></svg></figure>"`
  );
});

it("removes width and height", async () => {
  const result = processVizdomSvg(svg);

  expect(result).not.toContain(`width=`);
  expect(result).not.toContain(`height=`);
});

it("wraps in a figure with classes", async () => {
  const result = processVizdomSvg(svg);

  expect(result).toContain(`<figure class="beoe vizdom`);
});

it("is possible to add class", async () => {
  const result = processVizdomSvg(svg, "not-content");

  expect(result).toContain(`<figure class="beoe vizdom not-content`);
});
