name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # https://stackoverflow.com/questions/60491837/saving-cache-on-job-failure-in-github-actions
      - name: Cache turbo build restore
        uses: actions/cache/restore@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium

      - name: Build
        run: pnpm build --cache-dir=.turbo

      - name: Cache turbo build save
        uses: actions/cache/save@v3
        # if: always()
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}

      - name: Test
        run: pnpm test
